#!/usr/bin/env bash
set -e

cd $(dirname "$BASH_SOURCE[0]")/..

echo "running go fmt ..."
res=$(go fmt ./...)
if [ -n "$res" ]; then
  echo "$res"
  echo "gofmt failed..."
  exit 1
fi

git diff --exit-code 
if [ "$?" -gt "0" ]; then
  exit 1
fi

echo "running go mod vendor ..."
go mod vendor
git diff --exit-code
if [ "$?" -gt "0" ]; then
  exit 1
fi

echo "running golint ..."
golint -set_exit_status cmd internal

echo "running go vet ..."
go vet ./...

echo "running tests ..."
cd internal
go test -cover -race ./... $@
